# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton2.setGeometry(QtCore.QRect(70, 100, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton2.setFont(font)
        self.radioButton2.setObjectName("radioButton2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 230, 511, 87))
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setOverwriteMode(False)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(60, 30, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.radioButton1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton1.setGeometry(QtCore.QRect(70, 70, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton1.setFont(font)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton3.setGeometry(QtCore.QRect(70, 130, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton3.setFont(font)
        self.radioButton3.setObjectName("radioButton3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFlle = QtWidgets.QMenu(self.menubar)
        self.menuFlle.setObjectName("menuFlle")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFlle.addAction(self.actionSave)
        self.menuFlle.addAction(self.actionClose)
        self.menuOption.addAction(self.actionCopy)
        self.menuOption.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFlle.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #Start:I added these codes to do some function
        self.actionClose.triggered.connect(lambda: self.clicked("Closed now"))
        self.actionSave.triggered.connect(lambda: self.clicked("Stored now"))
        self.actionCopy.triggered.connect(lambda: self.clicked("Copy now"))
        self.actionPaste.triggered.connect(lambda: self.clicked("Paste now"))
        #End

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton2.setText(_translate("MainWindow", "C"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Type here"))
        self.label1.setText(_translate("MainWindow", "CHOOSE YOUR LANGUAGE"))
        self.radioButton1.setText(_translate("MainWindow", "C++"))
        self.radioButton3.setText(_translate("MainWindow", "Python"))
        self.label_2.setText(_translate("MainWindow", "Tell me about yourself"))
        self.menuFlle.setTitle(_translate("MainWindow", "File"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
    #Start:I added these codes to do some function
    def clicked(self,text):
        self.label1.setText(text) # label 1 is changed
        self.label1.adjustSize()
    #End

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
